# IMAGEN BASE
FROM eclipse-temurin:17.0.12_7-jdk

# INFORMAR EL PUERTO DONDE SE EJECUTA EL CONTENEDOR (INFORMATIVO)
EXPOSE 8080

# DEFINIR DIRECTORIO RAIZ DE NUESTRO CONTENEDOR
WORKDIR /root

# COPIAR EL ARCHIVO POM Y CONFIGURACIONES DE MAVEN
COPY ./pom.xml /root
COPY ./.mvn /root/.mvn
COPY ./mvnw /root

# COPIAR LA LIBRERIA LOCAL DENTRO DEL CONTENEDOR
COPY ./lib /root/lib

# DESCARGAR LAS DEPENDENCIAS
RUN ./mvnw dependency:go-offline

# COPIAR EL CÓDIGO FUENTE DENTRO DEL CONTENEDOR
COPY ./src /root/src

# CONSTRUIR LA APLICACIÓN
RUN ./mvnw clean install -DskipTests

# LEVANTAR LA APLICACIÓN CUANDO EL CONTENEDOR INICIE
ENTRYPOINT ["java","-jar","/root/target/bot-tiktok-0.0.1-SNAPSHOT.jar"]
